services:
  app:
    build: .
    ports:
      - "${APP_PORT}:7777"  # Используем переменную для порта хоста
    env_file:
      - .env  # Подключаем файл .env
    container_name: starter
    networks:
      - temporal-network
  worker:
    build: .
    container_name: worker
    env_file:
      - .env  # Подключаем файл .env
    command: ["python", "worker.py"]
    networks:
      - temporal-network

networks:
  temporal-network:
    external: true
    name: temporal-network